apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messenger
  template:
    metadata:
      labels:
        app: messenger
    spec:
      containers:
        - name: app
          image: your-dockerhub/messenger
          ports:
            - containerPort: 8000